version: '3.2'
services:
  mk.demo.gateway:
    image: mk.demo.gateway.img
    build:
      context: .
      dockerfile: ./Gateways/Mk.Demo.Gateway/Dockerfile
    ports:
      - target: 80                    # 容器端口
        published: 44502              # 宿主机端口
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - type: bind
        source: /usr/local/logs/App/Mk.Demo.Gateway/Logs
        target: /app/Logs
    container_name: mk.demo.gateway
    networks:
      - my-net

  mk.demob.api:
    image: mk.demob.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoB/src/Mk.DemoB.HttpApi.Host/Dockerfile
    ports:
      - target: 80                    
        published: 44302              
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - type: bind
        source: /usr/local/logs/App/Mk.DemoB/Logs
        target: /app/Logs
    networks:
      - my-net
    container_name: mk.demob.api
    depends_on:
      - mk.demo.gateway
      - mk.democ.api

  mk.democ.api:
    image: mk.democ.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoC/src/Mk.DemoC.HttpApi.Host/Dockerfile
    ports:
      - target: 80                    
        published: 44402              
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    volumes:
      - type: bind
        source: /usr/local/logs/App/Mk.DemoC/Logs
        target: /app/Logs
    networks:
      - my-net
    container_name: mk.democ.api
    depends_on:
      - mk.demo.gateway

networks:
  my-net:
    driver: bridge