version: '3.2'
services:
  mk.demo.gateway:
    image: mk.demo.gateway.img
    build:
      context: .
      dockerfile: ./Gateways/Mk.Demo.Gateway/Dockerfile
    ports:
      - '44502:44502'
    environment:
      - ASPNETCORE_URLS=http://localhost:44502
    volumes:
      - type: bind
        source: /e/Code/open_source/Abp/Leopard.Abp/Docker/App/Mk.Demo.Gateway/Logs
        target: /app/Logs
    container_name: mk.demo.gateway
    networks:
      - my-net

  mk.demob.api:
    image: mk.demob.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoB/src/Mk.DemoB.HttpApi.Host/Dockerfile
    ports:
      - '44302:44302'
    environment:
      - ASPNETCORE_URLS=http://localhost:44302
    volumes:
      - type: bind
        source: /e/Code/open_source/Abp/Leopard.Abp/Docker/App/Mk.DemoB/Logs
        target: /app/Logs
    networks:
      - my-net
    container_name: mk.demob.api
    depends_on:
      - mk.demo.gateway
      - mk.democ.api

  mk.democ.api:
    image: mk.democ.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoC/src/Mk.DemoC.HttpApi.Host/Dockerfile
    ports:
      - '44402:44402'
    environment:
      - ASPNETCORE_URLS=http://localhost:44402
    volumes:
      - type: bind
        source: /e/Code/open_source/Abp/Leopard.Abp/Docker/App/Mk.DemoC/Logs
        target: /app/Logs
    networks:
      - my-net
    container_name: mk.democ.api
    depends_on:
      - mk.demo.gateway

networks:
  my-net:
    driver: bridge
