version: '3.4'
services:
    mk.demob.api:
        image: mk.demob.api
        build:
            context: .
            dockerfile: ./Mk.DemoB/src/Mk.DemoB.HttpApi.Host/Dockerfile
        ports:
            - '44302:44302'
        environment:
            - ASPNETCORE_URLS=http://*:44302
        volumes:
            - /app/Logs:/e/Code/open_source/Abp/Leopard.Abp/Docker/App/Mk.DemoB/Logs
        networks:
            - my-net
        depends_on:
            - mk.democ.api
    mk.democ.api:
        image: mk.democ.api
        build:
            context: .
            dockerfile: ./Mk.DemoC/src/Mk.DemoC.HttpApi.Host/Dockerfile
        ports:
            - '44402:44402'
        environment:
            - ASPNETCORE_URLS=http://*:44402
        volumes:
            - /app/Logs:/e/Code/open_source/Abp/Leopard.Abp/Docker/App/Mk.DemoC/Logs
        networks:
            - my-net
    consul:
        image: consul
        build:
            context: .
            dockerfile: .Environment/Dockerfile
        ports:
            - '8500:8500'
        networks:
            - my-net
networks:
    my-net:
        driver: bridge