version: '3.2'

services:
  nginx:
    image: nginx.img
    build:
      context: nginx/
    restart: always
    ports:
      - '8081:80'
    volumes:
      - type: bind
        source: /usr/local/data/env/nginx/logs
        target: /var/log/nginx
      - type: bind
        source: /usr/local/data/env/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - my-net
      
networks:
  my-net:
    driver: bridge
